# fly.toml file generated for genex-logs on 2023-04-17T22:14:01-04:00

app = "genex-logs"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "iad"
processes = []

[build]
  image = "ghcr.io/superfly/fly-log-shipper:latest"

[env]

[experimental]
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8686

